"use client"

import { useState } from "react"
import { BookOpen, Upload, Sparkles, Target } from "lucide-react"
import { Card } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Button } from "@/components/ui/button"
import { FileUpload } from "@/components/FileUpload"
import { TopicSearch } from "@/components/TopicSearch"
import { QuestionList } from "@/components/QuestionList"
import { QuestionDetail } from "@/components/QuestionDetail"
import { CollapsibleSidebar } from "@/components/CollapsibleSidebar"
import type { Question, QuizState } from "@/types/quiz"

const Index = () => {
  const [quizState, setQuizState] = useState<QuizState>({
    questions: [],
    selectedQuestion: null,
    showAnswer: false,
  })

  const handleQuestionsLoaded = (newQuestions: Question[]) => {
    setQuizState((prev) => ({
      ...prev,
      questions: [...prev.questions, ...newQuestions],
    }))
  }

  const handleClearAutoGenerated = () => {
    setQuizState((prev) => ({
      ...prev,
      questions: prev.questions.filter((q) => !q.id.startsWith("generated-")),
      selectedQuestion:
        prev.selectedQuestion && prev.selectedQuestion.id.startsWith("generated-") ? null : prev.selectedQuestion,
    }))
  }

  const handleClearUploaded = () => {
    setQuizState((prev) => ({
      ...prev,
      questions: prev.questions.filter((q) => q.id.startsWith("generated-")),
      selectedQuestion:
        prev.selectedQuestion && !prev.selectedQuestion.id.startsWith("generated-") ? null : prev.selectedQuestion,
    }))
  }

  const handleQuestionSelect = (question: Question) => {
    setQuizState((prev) => ({
      ...prev,
      selectedQuestion: question,
      showAnswer: false,
    }))
  }

  const handleToggleAnswer = () => {
    setQuizState((prev) => ({
      ...prev,
      showAnswer: !prev.showAnswer,
    }))
  }

  const currentQuestionIndex = quizState.selectedQuestion
    ? quizState.questions.findIndex((q) => q.id === quizState.selectedQuestion?.id)
    : -1

  const handlePrevious = () => {
    if (currentQuestionIndex > 0) {
      const prevQuestion = quizState.questions[currentQuestionIndex - 1]
      handleQuestionSelect(prevQuestion)
    }
  }

  const handleNext = () => {
    if (currentQuestionIndex < quizState.questions.length - 1) {
      const nextQuestion = quizState.questions[currentQuestionIndex + 1]
      handleQuestionSelect(nextQuestion)
    }
  }

  const handleReset = () => {
    setQuizState((prev) => ({
      ...prev,
      showAnswer: false,
    }))
  }

  const handleQuestionSelectByIndex = (index: number) => {
    if (index >= 0 && index < quizState.questions.length) {
      handleQuestionSelect(quizState.questions[index])
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <CollapsibleSidebar
        questionCount={quizState.questions.length}
        selectedQuestionIndex={currentQuestionIndex}
        onQuestionSelect={handleQuestionSelectByIndex}
      >
        <Tabs defaultValue="upload" className="w-full">
          <TabsList className="grid w-full grid-cols-2 bg-sidebar-primary">
            <TabsTrigger value="upload" className="flex items-center gap-2 text-sidebar-foreground">
              <Upload className="w-4 h-4" />
              Upload
            </TabsTrigger>
            <TabsTrigger value="generate" className="flex items-center gap-2 text-sidebar-foreground">
              <Sparkles className="w-4 h-4" />
              Generate
            </TabsTrigger>
          </TabsList>

          <TabsContent value="upload" className="space-y-4 mt-4">
            <FileUpload onQuestionsLoaded={handleQuestionsLoaded} onClear={handleClearUploaded} />

            <Card className="p-4 bg-muted/30 border-border">
              <h4 className="font-semibold mb-2 text-card-foreground">Excel Format:</h4>
              <ul className="text-sm text-muted-foreground space-y-1">
                <li>
                  • <strong>Question:</strong> The quiz question
                </li>
                <li>
                  • <strong>Answer:</strong> The complete answer
                </li>
                <li>
                  • <strong>Topic:</strong> Product management topic
                </li>
                <li>
                  • <strong>Difficulty Level:</strong> Easy, Medium, or Hard
                </li>
              </ul>
            </Card>
          </TabsContent>

          <TabsContent value="generate" className="space-y-4 mt-4">
            <TopicSearch onQuestionsGenerated={handleQuestionsLoaded} onClear={handleClearAutoGenerated} />

            <Card className="p-4 bg-muted/30 border-border">
              <h4 className="font-semibold mb-2 text-card-foreground">Popular Topics:</h4>
              <div className="flex flex-wrap gap-2">
                {[
                  "Product Strategy",
                  "User Research",
                  "Analytics",
                  "Roadmapping",
                  "Stakeholder Management",
                  "A/B Testing",
                ].map((topic) => (
                  <span key={topic} className="px-2 py-1 bg-primary/10 text-primary text-xs rounded-md">
                    {topic}
                  </span>
                ))}
              </div>
            </Card>
          </TabsContent>
        </Tabs>

        <QuestionList
          questions={quizState.questions}
          selectedQuestion={quizState.selectedQuestion}
          onQuestionSelect={handleQuestionSelect}
        />
      </CollapsibleSidebar>

      <div className="flex-1 p-6 max-w-none">
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-2">
            <BookOpen className="w-8 h-8 text-primary" />
            <Target className="w-6 h-6 text-secondary" />
          </div>
          <h1 className="text-2xl font-bold text-foreground mb-1">
            Product Tank Bengaluru
            <span className="text-primary ml-1">Quiz!</span>
          </h1>
          <p className="text-muted-foreground">Think, Answer, Learn!</p>
        </div>

        <div className="h-[calc(100vh-200px)]">
          {quizState.selectedQuestion ? (
            <QuestionDetail
              question={quizState.selectedQuestion}
              showAnswer={quizState.showAnswer}
              onToggleAnswer={handleToggleAnswer}
              currentIndex={currentQuestionIndex}
              totalQuestions={quizState.questions.length}
              onPrevious={handlePrevious}
              onNext={handleNext}
              onReset={handleReset}
            />
          ) : (
            <Card className="p-12 text-center h-full flex items-center justify-center bg-card border-border">
              <div className="space-y-6 max-w-md">
                <Target className="w-20 h-20 text-muted-foreground mx-auto" />
                <div className="space-y-3">
                  <h3 className="text-3xl font-bold text-card-foreground">Ready to Start?</h3>
                  <p className="text-muted-foreground text-lg leading-relaxed">
                    {quizState.questions.length === 0
                      ? "Upload an Excel file or generate questions from a topic to begin your quiz journey."
                      : "Select a question from the sidebar to view it in detail and test your knowledge."}
                  </p>
                </div>
                {quizState.questions.length > 0 && (
                  <Button
                    onClick={() => handleQuestionSelect(quizState.questions[0])}
                    className="mt-6 px-8 py-3 text-base"
                  >
                    Start with First Question
                  </Button>
                )}
              </div>
            </Card>
          )}
        </div>
      </div>
    </div>
  )
}

export default Index
